CREATE DATABASE IF NOT EXISTS gym_db;
USE gym_db;

CREATE TABLE IF NOT EXISTS gym (
  g_id INT PRIMARY KEY AUTO_INCREMENT,
  g_name VARCHAR(255) NOT NULL,
  g_location VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS member (
  m_id INT PRIMARY KEY AUTO_INCREMENT,
  m_name VARCHAR(255) NOT NULL,
  m_dob DATE NOT NULL,
  m_gender CHAR(1) NOT NULL,
  m_info VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS equipment (
  e_id INT PRIMARY KEY AUTO_INCREMENT,
  e_name VARCHAR(255) NOT NULL,
  e_type VARCHAR(255) NOT NULL
);
